# Task -6  Numpy 

## Arrays



In [2]:
import numpy
def arrays(arr):
    arr1 = numpy.array(arr, dtype = float)
    arr2 = numpy.array(arr[::-1], dtype = float)
    return arr2
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## Shape and Reshape



In [3]:
import numpy as np
arr=input().strip().split(' ')
arr=np.array(arr,int)
print(np.reshape(arr,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose and Flatten

In [5]:
import numpy
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for i in range(n)], int)
print (array.transpose())
print (array.flatten())

2 2 
1 2 
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


## Concatenate



In [6]:
import numpy

X, Y, Z = map(int, input().split())
array = numpy.array([input().split() for i in range(X+Y)], int)

print(array)

4 3 2 
1 2 
1 2 
1 2 
1 2 
3 4 
3 4 
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Zeros and Ones



In [7]:

import numpy

def arrays(arr):
    arr1 = numpy.array(arr, dtype = int)
    arr2 = numpy.zeros(arr1, dtype = int)
    arr3 = numpy.ones(arr1, dtype = int)
    return arr2, arr3

arr = input().strip().split(' ')
arr2, arr3 = arrays(arr)

print(arr2)
print(arr3)

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Eye and Identity



In [8]:
import numpy
numpy.set_printoptions(sign=' ')

N, M = map(int, input().split())
eye = numpy.eye(N, M)
print(eye)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Array Mathematics



In [1]:
import numpy as np
n,m=map(int,input().split())
A=np.array([input().split()for i in range(n)],dtype=int)
B=np.array([input().split()for i in range(n)],dtype=int)
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)


1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Floor, Ceil and Rint

In [2]:
import numpy as np

np.set_printoptions(sign=" ")
arr=np.array(input().split(),dtype=float)
f=np.floor(arr)
c=np.ceil(arr)
r=np.rint(arr)
print(f)
print(c)
print(r)


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Sum and Prod



In [3]:
import numpy as np
n,m=map(int,input().split())
arr=np.array([input().split() for i in range(n)],dtype=int)
sumArray=np.sum(arr, axis=0)
product=np.product(sumArray)
print(product)


2 2
1 2 
3 4
24


## Min and Max



In [4]:
import numpy
N, M = map(int, input().split())

A = numpy.array([input().split() for i in range(N)],dtype = int)
print(numpy.max(numpy.min(A, axis=1), axis=0))


4 2
1 2 
2 3 
3 4 
5 6
5


## Dot and Cross



In [7]:
import numpy
N = int(input())
A = numpy.array([input().split() for i in range(N)], dtype =int)
B = numpy.array([input().split() for i in range(N)], dtype =int)
C = numpy.dot(A,B)
print(C)


2
1 2
2 3
4 5 
4 4
[[12 13]
 [20 22]]


## Inner and Outer

In [8]:
import numpy as np

a = np.array(input().split() , int)
b = np.array(input().split() , int)
print(np.inner(a,b),np.outer(a,b),sep='\n')


0 1
2 3
3
[[0 0]
 [2 3]]


## Polynomials

In [9]:
import numpy
m = numpy.array(input().split(), float)
n = float(input())
print(numpy.polyval(m, n))

1.1 2 3
0
3.0


## Linear Algebra

In [11]:
import numpy

numpy.set_printoptions(legacy='1.13')

N = int(input())

A = numpy.array([input().split() for i in range(N)], float)
print(numpy.linalg.det(A))


2 
1.1 1.1
1.1 1.1
0.0
